# Generated by Django 4.2 on 2024-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='homepage_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
