# Generated by Django 4.2 on 2024-07-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0006_profile_homepage_link_profile_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='website_link',
        ),
    ]
