# Generated by Django 4.2 on 2024-07-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0007_rename_homepage_link_profile_website_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_bio',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
